# Generated by Django 5.2 on 2026-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='user_pass1',
            new_name='pass1',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='user_pass2',
            new_name='pass2',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='user_name',
            new_name='username',
        ),
    ]
